#!/usr/bin/expect
# 2014-12-12 toby

# connects to ftp.omim.org and grabs two files

set timeout 20

set file1 [lindex $argv 0]
set file2 [lindex $argv 1]

set email "tongli@scripps.edu"

spawn ftp ftp.omim.org

expect "Name"
send "anonymous\r"
expect "Password:"
send "$email\r"

expect "ftp>"
send "ls\r"

expect "ftp>"
send "cd omim\r"

expect "ftp>"
send "ls\r"

expect "ftp>"
send "get $file1\r"

expect "ftp>"
send "get $file2\r"

expect "ftp>"
send "exit\r"

expect eof
